
// document.getElementById( "id" );
  // It will either return
    // A single DOM node that it finds
    // Or null
  // Uses DOM traversal behind the scenes

var mainHeading = document.getElementById("mainHeading");
var bill = document.getElementById("bill");
var importantParagraph = document.getElementById("important");


// document.getElementsByTagName( "tag" )
  // It will return a DOM collection (very similar to array)
    // It could be empty
    // It could contain a list of individual DOM nodes

// Create allParagraphs by selecting every p tag
var allParagraphs = document.getElementsByTagName("p");
// Create var allImages by selecting all img tags
var allImages = document.getElementsByTagName("img");

var allListItems = document.getElementsByTagName("li");

for (var index = 0; index < allListItems.length; index += 1) {
  var currentItem = allListItems[index];
  var itemText = currentItem.innerText;
  console.log(itemText);
}

// Traverse the DOM and create a variable of all images
  // Loop through all of the images
    // For each iteration, create a variable called currentImage, and log it out
var allImages = document.getElementsByTagName("img");
for (var i = 0; i < allImages.length; i += 1) {
  var currentImage = allImages[i];
  console.log(currentImage);
}

// document.getElementsByClassName( "class" );
console.clear();
var allTodos = document.getElementsByClassName("todo");
  // Returns a DOM Collection (similar to an array)

for (var j = 0; j < allTodos.length; j++) {
  var todo = allTodos[j]; // Returns a DOM node
  console.log(todo);
}

// document.querySelector( "any valid CSS" );
  // It will return the first thing it finds or null

var firstImage = document.querySelector("img");
var bill = document.querySelector("#bill");
var firstCage = document.querySelector(".cage");

// document.querySelectorAll("any valid CSS");
  // It will return a DOM Collection (similar to an array), it will either have DOM nodes in it or it will be empty

var allLorem = document.querySelectorAll(".lorem");
console.log(allLorem);

// I want to select all lis that are within a ul
var unorderedListItems = document.querySelectorAll("ul li");
console.log(unorderedListItems);

console.clear();

// DOM_NODE.getAttribute("attributeName");
var firstImage = document.querySelector("img");
var imageSource = firstImage.getAttribute("src");
console.log(imageSource);

// I want to change the image of bill to actually be an image of Steven Segal
var desiredSource = "http://stevensegallery.com/200/200";
firstImage.setAttribute("src", desiredSource);

// Find the element that I care about - .ga
  // What attribute do you care about? - href
    // log this out
var gaLink = document.querySelector(".ga");
var currentHref = gaLink.getAttribute("href");
console.log(currentHref);

var desiredHref = "https://generalassemb.ly";
gaLink.setAttribute("href", desiredHref);
console.log( gaLink.getAttribute("href") );

// I want to change the text from a Link to GA to a Link to General Assembly
var currentText = gaLink.innerText;
console.log(currentText);

gaLink.innerText = "A Link to General Assembly (UPDATED)";
gaLink.innerText += "!!!";

console.clear();

// Select all list items within an ordered list
  // Loop through each one of them and create a variable looking at the current todo item
    // Print out the current text
    // Update the text to something like TODO #1
    // Print out the new text
var listItems = document.querySelectorAll("ol li");

for (var i = 0; i < listItems.length; i += 1) {
  var currentTodo = listItems[i];
  var currentText = currentTodo.innerText;
  currentTodo.innerText = "TODO #" + (i + 1);
  console.log( currentTodo.innerText );
}

console.clear();

// node.style._______ = "";

var body = document.body;
// Create a variable called body
// Change the background color to be _____ lightslategray
body.style.background = "lightslategray";
// Change the font size to be 50px
body.style.fontSize = "50px";
// Change the default font colour to be salmon
body.style.color = "salmon";
body.style.textAlign = "center";

// Select the link - .ga
var ga = document.querySelector(".ga");
// Remove the underline
ga.style.textDecoration = "none";
// Change the color to hotpink
ga.style.color = "hotpink";
// Change the display to block
ga.style.display = "block";

console.clear();

var body = document.body;
// body.innerHTML = ""; // Empty the page

var newParagraph = document.createElement("p");
// This creates a DOM node but it is not on the page!

newParagraph.innerHTML = "Generated by JS";
newParagraph.style.textTransform = "uppercase";

body.appendChild( newParagraph );

// Create, Manipulate, and Inject

// Create a new H2
var h2 = document.createElement("h2");
// Set the inner HTML to be "DYNAMIC"
h2.innerHTML = "DYNAMIC";
// Change the style of it text align right
h2.style.textAlign = "right";
// Find the element with the class of dynamic
var div = document.querySelector(".dynamic");
// Append the new H2 to it
div.appendChild( h2 );


for (var i = 1; i <= 100; i++) {
  // Create an image
  var newImage = document.createElement("img");
    // <img>
  // Set the source to be http://fillmurray.com/205/205
  newImage.setAttribute("src", "http://fillmurray.com/205/205");
    // <img src="http://fillmurray.com/205/205">
  // Set the display block
  newImage.style.display = "block";
  // Append the image to .dynamic
  var dynamicDiv = document.querySelector(".dynamic");
  dynamicDiv.appendChild( newImage );
    // Do this 200 times if you can!
}




// DOM_NODE.classList
// DOM_NODE.classList.add("someclass");
// DOM_NODE.classList.remove("someclass");

var dynamicDiv = document.querySelector(".dynamic");
var currentClasses = dynamicDiv.classList;
console.log(currentClasses);

dynamicDiv.classList.add("none");
dynamicDiv.classList.remove("none");
